### ISSUE TITLE
Install generator not found

### ISSUE THREAD

**Issue by bbugh** [samesystem/graphql_rails#138]
Hi 👋 this project looks awesome. I want to test it out, but unfortunately I'm having an issue after install. The generator does not appear to be available:

```
Could not find generator 'graphql_rails:install'. Maybe you meant 'graphql:install', 'responders:install' or 'pundit:install'
Run `rails generate --help` for more options.
```

I confirmed that it is not in my list when I do `rails generate`.

Bundle confirms the gem is installed:

```
Using graphql_rails 0.8.0
```

This is a Rails 5.2 app.

**Comment by povilasjurcys** [comment]
hey @bbugh documentation is always shows what you can do with `master` branch code. To workaround this issue you can add:

```
gem 'graphql_rails', github: 'samesystem/graphql_rails', branch: 'master'
```

Or you can wait 1-2 weeks. Planning to release 1.0.0 version which will include all features mentioned in documentation.

If you still need v0.8.0 version documentation, then please check https://github.com/samesystem/graphql_rails/tree/v0.8.0

**Comment by povilasjurcys** [comment]
just released new version of graphql_rails which includes install generator
