### ISSUE TITLE
Incomplete schema in multithreaded environment.

### ISSUE THREAD

**Issue by jusmat** [samesystem/graphql_rails#178]
When working with multithreaded server, schema generation seems to be generated faulty in one of the async requests.

**Reproduction steps**
- Start up new server (so the schema is not set yet)
- Fire multiple async graphql requests. If your schema is big enough (takes some time to be generated) you'll experience one of the requests to fail with messages from `graphql` gem indicating that some types are without fields.
```Field Query.users's return type is invalid: User must define at least 1 field. 0 defined.```

As this is tricky to reproduce, you can do it from rails console too.
`5.times { Thread.new { ::GraphqlRouter.graphql_schema } }`. One of the threads will fail and throw an error.

**Comment by pucinsk** [comment]
Hello, @jusmat  (Sveiks ;D)

Mhm. I think I have a clue when it goes wrong. 
When I was working on [nested graphql types issue](https://github.com/samesystem/graphql_rails/pull/166) I needed to ensure that type names are uniq, so I added `SecureRandom.hex` [here](https://github.com/samesystem/graphql_rails/blob/master/lib/graphql_rails/model/configurable.rb#L18)

It is used to find (or define if it's not found) graphql type [here](https://github.com/samesystem/graphql_rails/blob/965aaf6d60b12ce2d7d2a36077117476a60a38fc/lib/graphql_rails/model/find_or_build_graphql_type_class.rb#L19). 

My guess is `SecureRandom.hex` does not ensure this uniqness across threads so whole schema generation process fails.
Possible solution: Replace `SecureRandom.hex` with something better.

**Comment by jusmat** [comment]
@pucinsk you were right on the place where it fails, however, it fails a bit differently. The problem is that constant is defined first, and then only afterwards the fields are assigned. Which in case we receive any more requests during the definition and field assignment - they use type constant without any fields. Which leads to execution errors.

**Comment by jusmat** [comment]
For anyone having this issue, preloading your schema o app boot will fix it. Not planning to work on this unless it gets problematic again.
