### ISSUE TITLE
Issue with dynamic type definition

### ISSUE THREAD

**Issue by devaudrius** [samesystem/graphql_rails#188]
Lets assume I have two models `Foo` and `Bar`

```
class Foo < ApplicationRecord
  ...
  has_many :bars
  ...

  graphql do |c|
    c.attribute :id, type: :id
    ...
    c.attribute :bars, type: Bar.graphql.graphql_type.to_list_type
  end
end
```

```
class Bar < ApplicationRecord
  ...
  has_many :foos
  ...

  graphql do |c|
    c.attribute :id, type: :id
    ...
    c.attribute :foos, type: Foo.graphql.graphql_type.to_list_type
  end
end
```

I would expect `bars` to appear as `Foo` type's attributes, but it doesn't, unless I remove `c.attribute :foos, type: Foo.graphql.graphql_type.to_list_type` from `Bar`'s graphql attributes definition, or change dynamic type definition `Bar.graphql.graphql_type.to_list_type` to `'[Bar]'`

**Comment by pucinsk** [comment]
The correct way to define list type would be using "square-brackets" syntax: 
```ruby
class Bar < ApplicationRecord
  ...
  has_many :foos
  ...

  graphql do |c|
    c.attribute :id, type: :id
    ...
    c.attribute :foos, type: '[Foo]'
  end
end
```

**Comment by povilasjurcys** [comment]
hey @devaudrius , defining types as `'[Bar]'` is the preferred way and you should use it as much as possible. `Foo.graphql.graphql_type.to_list_type` should be used only when you want to mix types `graphql_rails` types with `graphql-ruby` or doing some meta-programming.

**Comment by jusmat** [comment]
@povilasjurcys that's correct, string definition seems to be working. But this is one of those nice to have features, in my opinion. Would be nice if it worked disregarding the type of definition used.
