### ISSUE TITLE
Release automation

### ISSUE THREAD

**Issue by rbviz** [samesystem/graphql_rails#206]
With automated CI, we currently lack automated/semi-automated release flow. 
There's no obvious release rules or guidelines, so this needs to be discussed first.

**Comment by povilasjurcys** [comment]
I'm not against it - it would be nice if someone could take the lead on that. But we do like ~8 releases a year which is not that much manual work and I have no idea how much time would it take to automate it. Closing this issue as this is a very minor issue without anyone willing to do it
